### ISSUE TITLE
Hey this is my first issue!

### ISSUE THREAD

**Issue by janeon** [ai-xiaihai/ai-xiaihai.github.io#6]
These are my issues, please lemme know how problematic they are 🙇‍♀️

**Comment by jhsieh2** [comment]
I disapprove, your issue is invalid and stupid. Go make yourself useful

**Comment by janeon** [comment]
You're being disrespectful and dumb. Your code sucks and you have no place judging my issue

**Comment by jhsieh2** [comment]
Not only are you fat, you also don't know how to make issues

**Comment by ai-xiaihai** [comment]
@janeon @jhsieh2 stop arguing or you are both banned from this repo.
Thank you and have a good day.

**Comment by janeon** [comment]
No, @jhsieh2 is being stupid and disrespectful
